#!/usr/bin/env bash

sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
add_repo="$(which add-apt-repository)"
if [ $? -ne 0 ]; then
    sudo apt-get install -y software-properties-common
fi
sudo apt-add-repository https://cli.github.com/packages
sudo apt update
sudo apt install gh
