#!/usr/bin/env bash

TMP_DIR="$(mktemp -d)"
curl -sL https://github.com/arduino/arduino-cli/releases/download/0.14.0/arduino-cli_0.14.0_Linux_64bit.tar.gz -o "$TMP_DIR/arduinocli.tgz"
tar -xzf "$TMP_DIR/arduinocli.tgz" -C "$TMP_DIR"
sudo cp "$TMP_DIR/arduino-cli" "/usr/local/bin"
rm -Rf "$TMP_DIR"
/usr/local/bin/arduino-cli config init
/usr/local/bin/arduino-cli core update-index
