#!/usr/bin/env bash

echo "Installing [terraform]"
curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
add_repo="$(which add-apt-repository)"
if [ $? -ne 0 ]; then
    sudo apt-get install -y software-properties-common
fi
echo "here"
sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
sudo apt-get update
sudo apt-get install terraform
